ARG ARCH_TAG=x1164

FROM seancheung/alpinewine:$ARCH_TAG
LABEL maintainer="hoitaku"

ENV SCREEN="0 1280x1024x24"

RUN set -ex && \
    echo "Installing dependencies..." && \
    apk add --no-cache x11vnc && \
    echo "Clean Up..." && \
    rm -rf /var/cache/apk/*

COPY x11vnc.conf /etc/supervisor/conf.d/

EXPOSE 5900
